async function fetchMovieDetails(id: number): Promise<IMovieDetails | null> {
  // 'https://api.themoviedb.org/3/movie/1022789?language=en-US'
  const casts = await fetchMovieCasts(id);
  const movie: IMovieDetails = {
    adult: movieDetails.adult,
    backdrop_path: movieDetails.backdrop_path,
    budget: movieDetails.budget,
    genres: movieDetails.genres.map((genre) => genre.name),
    homepage: movieDetails.homepage,
    id: movieDetails.id,
    original_title: movieDetails.original_title,
    overview: movieDetails.overview,
    popularity: movieDetails.popularity,
    poster_path: movieDetails.poster_path,
    release_date: movieDetails.release_date,
    revenue: movieDetails.revenue,
    runtime: movieDetails.runtime,
    spoken_languages: movieDetails.spoken_languages.map((lang) => lang.english_name),
    status: movieDetails.status,
    tagline: movieDetails.tagline,
    title: movieDetails.title,
    video: movieDetails.video,
    vote_average: movieDetails.vote_average,
    vote_count: movieDetails.vote_count,
    imdb_id: movieDetails.imdb_id,
    media_type: "movie",
    casts: casts,
  };

  return await Promise.resolve<IMovieDetails | null>(movie);
}

async function fetchMovieCasts(id: number): Promise<string[]> {
  // 'https://api.themoviedb.org/3/movie/1022789/credits?language=en-US' \

  return movieCredits.cast.slice(0, 25).map((cast) => cast.name);
}

async function fetchTVShowDetails(id: number): Promise<ITVShowDetails | null> {
  // --url 'https://api.themoviedb.org/3/tv/series_id?language=en-US' \
  const casts = await fetchTVShowCasts(id);
  const tvShow: ITVShowDetails = {
    adult: mockedTVShow.adult,
    backdrop_path: mockedTVShow.backdrop_path,
    first_air_date: mockedTVShow.first_air_date,
    genres: mockedTVShow.genres.map((genre) => genre.name),
    homepage: mockedTVShow.homepage,
    id: mockedTVShow.id,
    in_production: mockedTVShow.in_production,
    last_air_date: mockedTVShow.last_air_date,
    name: mockedTVShow.name,
    number_of_episodes: mockedTVShow.number_of_episodes,
    number_of_seasons: mockedTVShow.number_of_seasons,
    original_name: mockedTVShow.original_name,
    overview: mockedTVShow.overview,
    popularity: mockedTVShow.popularity,
    poster_path: mockedTVShow.poster_path,
    spoken_languages: mockedTVShow.spoken_languages.map((lang) => lang.english_name),
    status: mockedTVShow.status,
    tagline: mockedTVShow.tagline,
    type: mockedTVShow.type,
    vote_average: mockedTVShow.vote_average,
    vote_count: mockedTVShow.vote_count,
    media_type: "tv",
    casts: casts,
  };
  return tvShow;
}
async function fetchTVShowCasts(id: number): Promise<string[]> {
  // --url 'https://api.themoviedb.org/3/tv/84773/credits?language=en-US' \

  return mockedTVShowCredits.cast.slice(0, 25).map((cast) => cast.name);
}
export { fetchMovieDetails, fetchTVShowDetails };

const mockedTVShow = {
  adult: false,
  backdrop_path: "/NNC08YmJFFlLi1prBkK8quk3dp.jpg",
  created_by: [
    {
      id: 1276959,
      credit_id: "5c0aa95c0e0a2638bc04bb53",
      name: "John D. Payne",
      original_name: "John D. Payne",
      gender: 2,
      profile_path: "/kR6m17NHQ6rbNEec91hjG4wWSpC.jpg",
    },
    {
      id: 1276960,
      credit_id: "5c0aa9469251414795047604",
      name: "Patrick McKay",
      original_name: "Patrick McKay",
      gender: 2,
      profile_path: null,
    },
  ],
  episode_run_time: [],
  first_air_date: "2022-09-01",
  genres: [
    {
      id: 10759,
      name: "Action & Adventure",
    },
    {
      id: 10765,
      name: "Sci-Fi & Fantasy",
    },
    {
      id: 18,
      name: "Drama",
    },
  ],
  homepage: "https://www.amazon.com/dp/B09QHC2LZM",
  id: 84773,
  in_production: true,
  languages: ["en"],
  last_air_date: "2024-08-29",
  last_episode_to_air: {
    id: 5348401,
    name: "The Eagle and the Sceptre",
    overview: "Isildur and an old friend reunite. Arondir grapples with change. Míriel faces rising opposition. Annatar counsels Celebrimbor.",
    vote_average: 5.3,
    vote_count: 16,
    air_date: "2024-08-29",
    episode_number: 3,
    episode_type: "standard",
    production_code: "",
    runtime: 67,
    season_number: 2,
    show_id: 84773,
    still_path: "/zMMkC9bGUT6MrtXGK6UAmSyApIC.jpg",
  },
  name: "The Lord of the Rings: The Rings of Power",
  next_episode_to_air: {
    id: 5348403,
    name: "Episode 4",
    overview: "",
    vote_average: 0,
    vote_count: 0,
    air_date: "2024-09-05",
    episode_number: 4,
    episode_type: "standard",
    production_code: "",
    runtime: null,
    season_number: 2,
    show_id: 84773,
    still_path: null,
  },
  networks: [
    {
      id: 1024,
      logo_path: "/ifhbNuuVnlwYy5oXA5VIb2YR8AZ.png",
      name: "Prime Video",
      origin_country: "",
    },
  ],
  number_of_episodes: 16,
  number_of_seasons: 2,
  origin_country: ["US"],
  original_language: "en",
  original_name: "The Lord of the Rings: The Rings of Power",
  overview:
    "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
  popularity: 2871.75,
  poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
  production_companies: [
    {
      id: 20580,
      logo_path: "/oRR9EXVoKP9szDkVKlze5HVJS7g.png",
      name: "Amazon Studios",
      origin_country: "US",
    },
    {
      id: 12,
      logo_path: "/2ycs64eqV5rqKYHyQK0GVoKGvfX.png",
      name: "New Line Cinema",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2022-09-03",
      episode_count: 36,
      id: 311036,
      name: "Specials",
      overview: "",
      poster_path: "/friNlTnLbsg38DRnUYLfKLdLBJE.jpg",
      season_number: 0,
      vote_average: 0,
    },
    {
      air_date: "2022-09-01",
      episode_count: 8,
      id: 114041,
      name: "Season 1",
      overview: "",
      poster_path: "/umRaUV2ku9MMtEunMQt3uCO1OgE.jpg",
      season_number: 1,
      vote_average: 6.7,
    },
    {
      air_date: "2024-08-29",
      episode_count: 8,
      id: 382474,
      name: "Season 2",
      overview:
        "Sauron has returned. Cast out by Galadriel, the Dark Lord must now rely on his own cunning to rebuild his strength and forge the legendary Rings of Power, threatening to bind all peoples of Middle-earth to his sinister will. Season 2 plunges its most beloved characters into a rising tide of darkness, challenging each to find his or her place in a world on the brink of calamity.",
      poster_path: "/yNcPTNvcWbWifW0XvQtbrThA0nt.jpg",
      season_number: 2,
      vote_average: 5.8,
    },
  ],
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "Evil has had many names.",
  type: "Scripted",
  vote_average: 7.346,
  vote_count: 2668,
};
const mockedTVShowCredits = {
  cast: [
    {
      adult: false,
      gender: 1,
      id: 1321628,
      known_for_department: "Acting",
      name: "Morfydd Clark",
      original_name: "Morfydd Clark",
      popularity: 67.503,
      profile_path: "/rVc9M8pojcY7aHyKpx3iCZKWYIs.jpg",
      character: "Galadriel",
      credit_id: "5e1e8a5d5c071b001163231d",
      order: 0,
    },
    {
      adult: false,
      gender: 2,
      id: 2309879,
      known_for_department: "Acting",
      name: "Charlie Vickers",
      original_name: "Charlie Vickers",
      popularity: 43.83,
      profile_path: "/nIn0RTnOukikIKiVwtzRwkpcJvy.jpg",
      character: "Sauron / Annatar",
      credit_id: "66439027f33ff64dcdcb5863",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1648346,
      known_for_department: "Acting",
      name: "Robert Aramayo",
      original_name: "Robert Aramayo",
      popularity: 31.947,
      profile_path: "/5CNx6hV7buItL1Icsc2AorP9AqE.jpg",
      character: "Elrond",
      credit_id: "5e14c3fc6c449c0016315c77",
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 1220087,
      known_for_department: "Acting",
      name: "Daniel Weyman",
      original_name: "Daniel Weyman",
      popularity: 19.265,
      profile_path: "/qONmQ0AIWPpFmWrmiupMEG7K9mF.jpg",
      character: "The Stranger",
      credit_id: "5fb15c71e24e3a0040e85bb1",
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 2138256,
      known_for_department: "Acting",
      name: "Markella Kavenagh",
      original_name: "Markella Kavenagh",
      popularity: 46.584,
      profile_path: "/wLXCCBQ6f456K2mQtbY8vgiOJoK.jpg",
      character: "Elanor 'Nori' Brandyfoot",
      credit_id: "5d70f9aa77c01f0c1a5a485f",
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 281527,
      known_for_department: "Acting",
      name: "Charles Edwards",
      original_name: "Charles Edwards",
      popularity: 12.494,
      profile_path: "/2mFLkYEMlqRSh630wwrcYzKoS1s.jpg",
      character: "Celebrimbor",
      credit_id: "60dde28f5690b5007faafe80",
      order: 5,
    },
    {
      adult: false,
      gender: 2,
      id: 1100144,
      known_for_department: "Acting",
      name: "Ismael Cruz Cordova",
      original_name: "Ismael Cruz Cordova",
      popularity: 26.895,
      profile_path: "/gx59ZkpGgGLEH79ciDgyWpUG8nt.jpg",
      character: "Arondir",
      credit_id: "5e1e8e60511d090014827426",
      order: 6,
    },
    {
      adult: false,
      gender: 2,
      id: 1274938,
      known_for_department: "Acting",
      name: "Owain Arthur",
      original_name: "Owain Arthur",
      popularity: 14.804,
      profile_path: "/rwUPaXPFkuR2e6MpMq8SWI8Yxsb.jpg",
      character: "Durin IV",
      credit_id: "5e1e8a475c071b001362df39",
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 172935,
      known_for_department: "Acting",
      name: "Lloyd Owen",
      original_name: "Lloyd Owen",
      popularity: 19.683,
      profile_path: "/xsBtLkxCedK1z4wfC11Q2ZBQa8Q.jpg",
      character: "Elendil",
      credit_id: "5fca325cd8e225003f90ed8c",
      order: 8,
    },
    {
      adult: false,
      gender: 1,
      id: 2056333,
      known_for_department: "Acting",
      name: "Sophia Nomvete",
      original_name: "Sophia Nomvete",
      popularity: 96.529,
      profile_path: "/wD9OMH6cddK2RsoCTQ22Ja4Uyjv.jpg",
      character: "Disa",
      credit_id: "5e1e8f05d9f4a600179a510f",
      order: 9,
    },
    {
      adult: false,
      gender: 2,
      id: 16373,
      known_for_department: "Acting",
      name: "Maxim Baldry",
      original_name: "Maxim Baldry",
      popularity: 23.007,
      profile_path: "/xjk6RuJrjpP5nIrfwh7QeRbTzdC.jpg",
      character: "Isildur",
      credit_id: "5e1f34a9511d09001683dae5",
      order: 10,
    },
    {
      adult: false,
      gender: 2,
      id: 2510411,
      known_for_department: "Acting",
      name: "Tyroe Muhafidin",
      original_name: "Tyroe Muhafidin",
      popularity: 9.257,
      profile_path: "/opKzRsU5iGJ8GDKO5HwC7ze5KHv.jpg",
      character: "Theo",
      credit_id: "5e1e8eeb511d090014827531",
      order: 11,
    },
    {
      adult: false,
      gender: 2,
      id: 589651,
      known_for_department: "Acting",
      name: "Trystan Gravelle",
      original_name: "Trystan Gravelle",
      popularity: 12.222,
      profile_path: "/ne38S64FWTktbfjt0nRTe69g5bd.jpg",
      character: "Pharazôn",
      credit_id: "6349081d021cee007dc061b0",
      order: 12,
    },
    {
      adult: false,
      gender: 1,
      id: 182272,
      known_for_department: "Acting",
      name: "Cynthia Addai-Robinson",
      original_name: "Cynthia Addai-Robinson",
      popularity: 29.186,
      profile_path: "/5eZAiWHtgiECm666CRemqMYdOlj.jpg",
      character: "Míriel",
      credit_id: "5fca30938261ee003e3dfc64",
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 239996,
      known_for_department: "Acting",
      name: "Benjamin Walker",
      original_name: "Benjamin Walker",
      popularity: 20.747,
      profile_path: "/jwM8BZ1hVcbzfs9jNndVmaocULF.jpg",
      character: "High King Gil-Galad",
      credit_id: "66d2b291f28dbeb3e5a80561",
      order: 14,
    },
    {
      adult: false,
      gender: 1,
      id: 2145794,
      known_for_department: "Acting",
      name: "Megan Richards",
      original_name: "Megan Richards",
      popularity: 6.752,
      profile_path: "/q66cIEIlt4ylFXVlgdLbYHuuUOw.jpg",
      character: "Poppy Proudfellow",
      credit_id: "5e1e8f14511d090014827590",
      order: 15,
    },
    {
      adult: false,
      gender: 1,
      id: 1921268,
      known_for_department: "Acting",
      name: "Ema Horvath",
      original_name: "Ema Horvath",
      popularity: 28.125,
      profile_path: "/4YindT5cKhekpAilc6q0scQeUQx.jpg",
      character: "Eärien",
      credit_id: "5df0db916a34480012c7e6a6",
      order: 16,
    },
    {
      adult: false,
      gender: 2,
      id: 93119,
      known_for_department: "Acting",
      name: "Geoff Morrell",
      original_name: "Geoff Morrell",
      popularity: 5.15,
      profile_path: "/zdbbOZPOb1VeAXh1idj9fKeHE87.jpg",
      character: "Waldreg",
      credit_id: "5fca324ab0040a0041264cd8",
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 1456729,
      known_for_department: "Acting",
      name: "Alex Tarrant",
      original_name: "Alex Tarrant",
      popularity: 5.953,
      profile_path: "/wfQwh9D4qOqFsaj9X0Lrk7GG6kI.jpg",
      character: "Valandil",
      credit_id: "5fca327643999b003d1682fe",
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 563559,
      known_for_department: "Acting",
      name: "Sam Hazeldine",
      original_name: "Sam Hazeldine",
      popularity: 21.375,
      profile_path: "/zyt5yR8hXMA9ZcwtL0yDadwvi4m.jpg",
      character: "Adar",
      credit_id: "66d27f87de9e844993c0d073",
      order: 19,
    },
  ],
  id: 84773,
};

const movieDetails = {
  adult: false,
  backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
  belongs_to_collection: {
    id: 1022790,
    name: "Inside Out Collection",
    poster_path: "/kvJqs0vm29U0xJa373wlzHb3FRh.jpg",
    backdrop_path: "/7U2m2dMSIfHx2gWXKq78Xj1weuH.jpg",
  },
  budget: 200000000,
  genres: [
    {
      id: 16,
      name: "Animation",
    },
    {
      id: 10751,
      name: "Family",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 35,
      name: "Comedy",
    },
  ],
  homepage: "https://movies.disney.com/inside-out-2",
  id: 1022789,
  imdb_id: "tt22022452",
  origin_country: ["US"],
  original_language: "en",
  original_title: "Inside Out 2",
  overview:
    "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  popularity: 2452.837,
  poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
  production_companies: [
    {
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
      name: "Walt Disney Pictures",
      origin_country: "US",
    },
    {
      id: 3,
      logo_path: "/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png",
      name: "Pixar",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2024-06-11",
  revenue: 1667589398,
  runtime: 97,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Make room for new emotions.",
  title: "Inside Out 2",
  video: false,
  vote_average: 7.686,
  vote_count: 3250,
};

const movieCredits = {
  id: 1022789,
  cast: [
    {
      adult: false,
      gender: 1,
      id: 56322,
      known_for_department: "Acting",
      name: "Amy Poehler",
      original_name: "Amy Poehler",
      popularity: 15.363,
      profile_path: "/rwmvRonpluV6dCPiQissYrchvSD.jpg",
      cast_id: 4,
      character: "Joy (voice)",
      credit_id: "631bd7450bb076007b78d023",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 1903874,
      known_for_department: "Acting",
      name: "Maya Hawke",
      original_name: "Maya Hawke",
      popularity: 45.423,
      profile_path: "/wWvtHBYDXIcpdjXmKAYUqsOXI17.jpg",
      cast_id: 7,
      character: "Anxiety (voice)",
      credit_id: "654ce72cd4653700c4e31b8c",
      order: 1,
    },
    {
      adult: false,
      gender: 1,
      id: 3020876,
      known_for_department: "Acting",
      name: "Kensington Tallman",
      original_name: "Kensington Tallman",
      popularity: 11.284,
      profile_path: "/tBqawwg2VJq1V4mZjAOFQ7fnXNW.jpg",
      cast_id: 51,
      character: "Riley (voice)",
      credit_id: "65eae45d5aba320186731060",
      order: 2,
    },
    {
      adult: false,
      gender: 1,
      id: 51998,
      known_for_department: "Acting",
      name: "Liza Lapira",
      original_name: "Liza Lapira",
      popularity: 23.873,
      profile_path: "/o3jvQAGWtxi5rEycslhC6CY8BWX.jpg",
      cast_id: 11,
      character: "Disgust (voice)",
      credit_id: "654ce92b5a5ed001003fff7d",
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 25147,
      known_for_department: "Acting",
      name: "Tony Hale",
      original_name: "Tony Hale",
      popularity: 22.384,
      profile_path: "/ar4uapp4w5wMkThZcqWUNMSTO8z.jpg",
      cast_id: 10,
      character: "Fear (voice)",
      credit_id: "654ce91567b61300e5dd0954",
      order: 4,
    },
    {
      adult: false,
      gender: 2,
      id: 59258,
      known_for_department: "Acting",
      name: "Lewis Black",
      original_name: "Lewis Black",
      popularity: 18.78,
      profile_path: "/1Yvp5dwnJ1UI0KtXGNhZ384wTgv.jpg",
      cast_id: 9,
      character: "Anger (voice)",
      credit_id: "654ce9001ac2927b2dd002bf",
      order: 5,
    },
    {
      adult: false,
      gender: 1,
      id: 169200,
      known_for_department: "Acting",
      name: "Phyllis Smith",
      original_name: "Phyllis Smith",
      popularity: 24.419,
      profile_path: "/h9w9pQbiderRWAC2mi7spjzuIGz.jpg",
      cast_id: 8,
      character: "Sadness (voice)",
      credit_id: "654ce8c72866fa10928b746d",
      order: 6,
    },
    {
      adult: false,
      gender: 1,
      id: 2195140,
      known_for_department: "Acting",
      name: "Ayo Edebiri",
      original_name: "Ayo Edebiri",
      popularity: 24.93,
      profile_path: "/zkTexmrBr5it1Xkm3XYE00hERHb.jpg",
      cast_id: 18,
      character: "Envy (voice)",
      credit_id: "65e9f9393d7454017dba07e7",
      order: 7,
    },
    {
      adult: false,
      gender: 1,
      id: 1469135,
      known_for_department: "Acting",
      name: "Lilimar",
      original_name: "Lilimar",
      popularity: 14.03,
      profile_path: "/cRerzbUsq0TiWe6z0VGtLHz4JOa.jpg",
      cast_id: 37,
      character: "Valentina (voice)",
      credit_id: "65ea226224b3330163b3316d",
      order: 8,
    },
    {
      adult: false,
      gender: 1,
      id: 3264370,
      known_for_department: "Acting",
      name: "Grace Lu",
      original_name: "Grace Lu",
      popularity: 3.278,
      profile_path: "/8M0B0LlwiXyBMaCCcp4nbyXSPCy.jpg",
      cast_id: 39,
      character: "Grace (voice)",
      credit_id: "65ea22866beaea01867acfb1",
      order: 9,
    },
    {
      adult: false,
      gender: 1,
      id: 4578518,
      known_for_department: "Acting",
      name: "Sumayyah Nuriddin-Green",
      original_name: "Sumayyah Nuriddin-Green",
      popularity: 2.683,
      profile_path: "/9yTDK4xUSAsC5fVY2bvgCaTnZ7L.jpg",
      cast_id: 38,
      character: "Bree (voice)",
      credit_id: "65ea22837c6de30163086af1",
      order: 10,
    },
    {
      adult: false,
      gender: 1,
      id: 586757,
      known_for_department: "Acting",
      name: "Adèle Exarchopoulos",
      original_name: "Adèle Exarchopoulos",
      popularity: 30.822,
      profile_path: "/zlto2xvsdzLnfzoZNnS6txzNO5l.jpg",
      cast_id: 54,
      character: "Ennui (voice)",
      credit_id: "663653e59590e3012cbc2db6",
      order: 11,
    },
    {
      adult: false,
      gender: 1,
      id: 2882,
      known_for_department: "Acting",
      name: "Diane Lane",
      original_name: "Diane Lane",
      popularity: 44.221,
      profile_path: "/pNNIs1bCQ2qFL9rekkV7utunUfl.jpg",
      cast_id: 13,
      character: "Mom (voice)",
      credit_id: "6552a2defd6fa100fee6f85e",
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 6677,
      known_for_department: "Acting",
      name: "Kyle MacLachlan",
      original_name: "Kyle MacLachlan",
      popularity: 26.509,
      profile_path: "/dNGPjhInyADHjiiYJAWsSUAIC7o.jpg",
      cast_id: 14,
      character: "Dad (voice)",
      credit_id: "6553eaeed4fe040139815934",
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 1294982,
      known_for_department: "Acting",
      name: "Paul Walter Hauser",
      original_name: "Paul Walter Hauser",
      popularity: 18.947,
      profile_path: "/hV2oiKF2xlDMXtuq3Si1TA4b6DA.jpg",
      cast_id: 20,
      character: "Embarrassment (voice)",
      credit_id: "65e9f95a1dcb770163ce61d8",
      order: 14,
    },
    {
      adult: false,
      gender: 1,
      id: 111513,
      known_for_department: "Acting",
      name: "Yvette Nicole Brown",
      original_name: "Yvette Nicole Brown",
      popularity: 19.223,
      profile_path: "/ghdt5K3noAdmWV2YFLWegLRuK3T.jpg",
      cast_id: 40,
      character: "Coach Roberts (voice)",
      credit_id: "65ea22d61dcb770163ce77fb",
      order: 15,
    },
    {
      adult: false,
      gender: 2,
      id: 1260038,
      known_for_department: "Acting",
      name: "Ron Funches",
      original_name: "Ron Funches",
      popularity: 10.132,
      profile_path: "/DtULMxPvAlOKfrwISxdEffIKlk.jpg",
      cast_id: 43,
      character: "Bloofy (voice)",
      credit_id: "65ea23326beaea01867ad066",
      order: 16,
    },
    {
      adult: false,
      gender: 2,
      id: 1756597,
      known_for_department: "Acting",
      name: "James Austin Johnson",
      original_name: "James Austin Johnson",
      popularity: 4.586,
      profile_path: "/g9y0aABiKtB1FOIKmklDlgRpDof.jpg",
      cast_id: 33,
      character: "Pouchy (voice)",
      credit_id: "65ea1d5424b333017cb3328b",
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 3602293,
      known_for_department: "Acting",
      name: "Yong Yea",
      original_name: "Yong Yea",
      popularity: 4.204,
      profile_path: "/mZX1dsTJBtiSE5LMCGAdq94UZsP.jpg",
      cast_id: 50,
      character: "Lance Slashblade (voice)",
      credit_id: "65ea239d389da10180d8472c",
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 137262,
      known_for_department: "Acting",
      name: "Steve Purcell",
      original_name: "Steve Purcell",
      popularity: 18.063,
      profile_path: "/8wdCJVDq7v4g5N9Qkv8D87B3Xne.jpg",
      cast_id: 65,
      character: "Deep Dark Secret (voice)",
      credit_id: "6652b9aaecfb5a929fa6f362",
      order: 19,
    },
    {
      adult: false,
      gender: 2,
      id: 64181,
      known_for_department: "Acting",
      name: "Dave Goelz",
      original_name: "Dave Goelz",
      popularity: 12.079,
      profile_path: "/gVwJIPP0cohKEFwgymTmzzkSX7E.jpg",
      cast_id: 34,
      character: "Mind Cop Frank (voice)",
      credit_id: "65ea1dbe3d7454017dba2bfd",
      order: 20,
    },
    {
      adult: false,
      gender: 2,
      id: 145446,
      known_for_department: "Directing",
      name: "Kirk R. Thatcher",
      original_name: "Kirk R. Thatcher",
      popularity: 11.304,
      profile_path: null,
      cast_id: 49,
      character: "Foreman (voice)",
      credit_id: "65ea23956beaea01867ad0c8",
      order: 21,
    },
    {
      adult: false,
      gender: 2,
      id: 7908,
      known_for_department: "Acting",
      name: "Frank Oz",
      original_name: "Frank Oz",
      popularity: 21.56,
      profile_path: "/mb2JbT8s6LIgaxj6QTph0NW1pmI.jpg",
      cast_id: 35,
      character: "Mind Cop Dave (voice)",
      credit_id: "65ea1dd972c13e0185c5769b",
      order: 22,
    },
    {
      adult: false,
      gender: 1,
      id: 1226294,
      known_for_department: "Acting",
      name: "Paula Pell",
      original_name: "Paula Pell",
      popularity: 7.279,
      profile_path: "/aQZsAcaac2zzLBMhb15O2mrSrpx.jpg",
      cast_id: 45,
      character: "Mom's Anger (voice)",
      credit_id: "65ea236a5aba320186716fed",
      order: 23,
    },
    {
      adult: false,
      gender: 1,
      id: 35515,
      known_for_department: "Acting",
      name: "June Squibb",
      original_name: "June Squibb",
      popularity: 14.342,
      profile_path: "/iohsuSDPcVAFr0NKQifM7qEJDFt.jpg",
      cast_id: 15,
      character: "Nostalgia (voice)",
      credit_id: "65a6c88c9ac535012d00129c",
      order: 24,
    },
    {
      adult: false,
      gender: 2,
      id: 12890,
      known_for_department: "Directing",
      name: "Pete Docter",
      original_name: "Pete Docter",
      popularity: 21.838,
      profile_path: "/xz46mHzo8apkVMxmrkMQvqakOL0.jpg",
      cast_id: 72,
      character: "Dad's Anger (voice)",
      credit_id: "666dc8bf1f47987ee1a7d276",
      order: 25,
    },
    {
      adult: false,
      gender: 1,
      id: 196502,
      known_for_department: "Acting",
      name: "Paula Poundstone",
      original_name: "Paula Poundstone",
      popularity: 3.856,
      profile_path: "/jfu3LSX48WbvcJ4NXmrdI48epLJ.jpg",
      cast_id: 46,
      character: "Forgetter Paula (voice)",
      credit_id: "65ea23717f4f21017bdbf939",
      order: 26,
    },
    {
      adult: false,
      gender: 2,
      id: 7907,
      known_for_department: "Acting",
      name: "John Ratzenberger",
      original_name: "John Ratzenberger",
      popularity: 25.002,
      profile_path: "/oRtDEOuIO1yDhTz5dORBdxXuLMO.jpg",
      cast_id: 47,
      character: "Fritz (voice)",
      credit_id: "65ea237c389da10162d6f9e1",
      order: 27,
    },
    {
      adult: false,
      gender: 1,
      id: 1224130,
      known_for_department: "Acting",
      name: "Sarayu Blue",
      original_name: "Sarayu Blue",
      popularity: 10.733,
      profile_path: "/zW1G9wSJ03iaSDToFxkMJaqGZLs.jpg",
      cast_id: 41,
      character: "Margie (voice)",
      credit_id: "65ea232572c13e0185c57c47",
      order: 28,
    },
    {
      adult: false,
      gender: 2,
      id: 1237,
      known_for_department: "Acting",
      name: "Flea",
      original_name: "Flea",
      popularity: 16.632,
      profile_path: "/nGQE7xf4YJeqO0a4lpFebhwI7R9.jpg",
      cast_id: 36,
      character: "Jake (voice)",
      credit_id: "65ea1e253d74540164b91ab6",
      order: 29,
    },
    {
      adult: false,
      gender: 2,
      id: 452205,
      known_for_department: "Acting",
      name: "Bobby Moynihan",
      original_name: "Bobby Moynihan",
      popularity: 18.2,
      profile_path: "/gOvwNz5joi5yWJ7dAhuF8WA2aas.jpg",
      cast_id: 44,
      character: "Forgetter Bobby (voice)",
      credit_id: "65ea23563d74540164b91de5",
      order: 30,
    },
  ],
};
