const getPopularMedia = async (page: number): Promise<IPopularMediaResponse | null> => {
  // https://api.themoviedb.org/3/trending/all/week?language=en-US'
  //   const url: string = `https://api.themoviedb.org/3/trending/all/week?language=en-US&api_key=${process.env.API_KEY}`;
  //   const urlObject = {
  //     href: "https://api.themoviedb.org/3/trending/all/week",
  //     query: { language: "en-US", api_key: process.env.API_KEY },
  //   };

  return await Promise.resolve<IPopularMediaResponse | null>(mockedPopularAllMedia);
};
async function getPopularMovies(page: number): Promise<IPopularMoviesResponse | null> {
  // https://api.themoviedb.org/3/trending/movie/week?language=en-US'
  return await Promise.resolve<IPopularMoviesResponse | null>(mockedPopularMovies);
}
async function getPopularTVShows(page: number): Promise<IPopularTVShowsResponse | null> {
  // https://api.themoviedb.org/3/trending/tv/week?language=en-US'
  return await Promise.resolve<IPopularTVShowsResponse | null>(mockedPopularTVShows);
}

export { getPopularMedia, getPopularMovies, getPopularTVShows };

const mockedPopularTVShows: IPopularTVShowsResponse = {
  page: 1,
  results: [
    {
      backdrop_path: "/NNC08YmJFFlLi1prBkK8quk3dp.jpg",
      id: 84773,
      name: "The Lord of the Rings: The Rings of Power",
      original_name: "The Lord of the Rings: The Rings of Power",
      overview:
        "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
      poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765, 18],
      popularity: 2871.75,
      first_air_date: "2022-09-01",
      vote_average: 7.346,
      vote_count: 2668,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/9Piw6Zju39bn3enIDLZzPfjMTBR.jpg",
      id: 102621,
      name: "KAOS",
      original_name: "KAOS",
      overview:
        "As discord reigns on Mount Olympus and almighty Zeus spirals into paranoia, three mortals are destined to reshape the future of humankind.",
      poster_path: "/dDBTUSl3tRsOeKC1jZugBSFHy9I.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 10765, 18],
      popularity: 367.035,
      first_air_date: "2024-08-29",
      vote_average: 7.42,
      vote_count: 44,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/woH18JkZMYhMSWqtHkPA4F6Gd1z.jpg",
      id: 239287,
      name: "Terminator Zero",
      original_name: "ターミネーター 0",
      overview:
        "A warrior from a post-apocalyptic future travels to 1997 to protect an AI scientist being hunted by an unfeeling — and indestructible — cyborg.",
      poster_path: "/v4sbn6IsJGAIZNHjdB4CprvS7zo.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10765, 10759],
      popularity: 734.415,
      first_air_date: "2024-08-29",
      vote_average: 7.617,
      vote_count: 47,
      origin_country: ["US", "JP"],
    },
    {
      backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
      id: 37854,
      name: "One Piece",
      original_name: "ワンピース",
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: "/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 35, 16],
      popularity: 288,
      first_air_date: "1999-10-20",
      vote_average: 8.719,
      vote_count: 4589,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      id: 94997,
      name: "House of the Dragon",
      original_name: "House of the Dragon",
      overview:
        "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 1025.42,
      first_air_date: "2022-08-21",
      vote_average: 8.395,
      vote_count: 4839,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      id: 1399,
      name: "Game of Thrones",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 1190.095,
      first_air_date: "2011-04-17",
      vote_average: 8.455,
      vote_count: 23758,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/ea6lO0I2wOtC0SiHWZPfg9zRKZo.jpg",
      id: 219652,
      name: "The Frog",
      original_name: "아무도 없는 숲속에서",
      overview:
        "One tranquil summer, a mysterious woman checks into a vacation rental — triggering events that disrupt the lives of the owner and those around him.",
      poster_path: "/uMl2TzRs1LzTR9jyRNHnf5keqMV.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ko",
      genre_ids: [9648, 80, 18],
      popularity: 340.561,
      first_air_date: "2024-08-23",
      vote_average: 6.815,
      vote_count: 27,
      origin_country: ["KR"],
    },
    {
      backdrop_path: "/5yeiwbK9LOpi7SiTklz1pOqYlBb.jpg",
      id: 252636,
      name: "Escape from the Trilateral Slopes",
      original_name: "边水往事",
      overview:
        "Trilateral Slopes, a tropical exotic melting pot teeming with all kinds of people, a place where prosperity and decay coexist. Shen Xing, a laborer who unexpectedly ends up here, crosses paths with Mr. Cai, a local wheeler-dealer navigating through the various forces at play. Together, they embark on an adventure, guided by a glimmer of kindness, as they face the struggle between staying and escaping. How will their story unfold in the midst of the disarray?",
      poster_path: "/89VKjiQxlSAYHZHX8U5e6D9WzRp.jpg",
      media_type: "tv",
      adult: false,
      original_language: "zh",
      genre_ids: [18],
      popularity: 207.566,
      first_air_date: "2024-08-16",
      vote_average: 7.4,
      vote_count: 5,
      origin_country: ["CN"],
    },
    {
      backdrop_path: "/oyZWiPvumwSYMrF2XbZH6yXQZ14.jpg",
      id: 107113,
      name: "Only Murders in the Building",
      original_name: "Only Murders in the Building",
      overview: "Three strangers share an obsession with true crime and suddenly find themselves wrapped up in one.",
      poster_path: "/bZubW4eLAk2zqk44fSWRDTFfcba.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 9648, 80],
      popularity: 889.84,
      first_air_date: "2021-08-31",
      vote_average: 8.328,
      vote_count: 1366,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/eCNkqS4OWVKmPTjFmL2CWYhlVOL.jpg",
      id: 130853,
      name: "Bad Monkey",
      original_name: "Bad Monkey",
      overview:
        "A detective turned restaurant inspector in Southern Florida is pulled into a world of greed and corruption after a tourist finds a severed arm while fishing. And yes, there's a monkey.",
      poster_path: "/sDbpr5VoxlcQvzvWFECr7bXCAwg.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 80],
      popularity: 485.629,
      first_air_date: "2024-08-13",
      vote_average: 7.2,
      vote_count: 37,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/2WBO3C7CjsOTT5wgi9Inn5iQhVv.jpg",
      id: 46195,
      name: "Monogatari",
      original_name: "化物語",
      overview:
        "Although there are still traces of the brief period he became a vampire, third-year high school student Koyomi Araragi is human again. He happens upon others with their own supernatural problems and finds that he can empathize. Koyomi becomes involved in their lives, seeking to help them and occasionally asking for advice from Meme Oshino, the homeless man who helped him become human again.",
      poster_path: "/snwMpEzwQAi7QShO0pYrs6lNygh.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 35, 18, 9648],
      popularity: 381.427,
      first_air_date: "2009-07-03",
      vote_average: 8.129,
      vote_count: 454,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/aGYVOLanNjLTvqlfdyp0mKBdFKH.jpg",
      id: 615,
      name: "Futurama",
      original_name: "Futurama",
      overview:
        "The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery company in the retro-futuristic 31st century.",
      poster_path: "/sdJcX2cXirwQurLLlrDLYov7hcD.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [16, 35, 10765],
      popularity: 735.612,
      first_air_date: "1999-03-28",
      vote_average: 8.4,
      vote_count: 3206,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg",
      id: 76479,
      name: "The Boys",
      original_name: "The Boys",
      overview:
        "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
      poster_path: "/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 10759],
      popularity: 1832.155,
      first_air_date: "2019-07-25",
      vote_average: 8.475,
      vote_count: 10320,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
      id: 110382,
      name: "Pachinko",
      original_name: "Pachinko",
      overview:
        "Follow the hopes and dreams of four generations of a Korean immigrant family beginning with a forbidden love and crescendos into a sweeping saga that journeys between Korea, Japan and America to tell the unforgettable story of war and peace, love and loss, triumph and reckoning.",
      poster_path: "/Ab9z43yotMYDzDNmXk8Uw9ZNIhx.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 324.816,
      first_air_date: "2022-03-24",
      vote_average: 7.9,
      vote_count: 175,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
      id: 1429,
      name: "Attack on Titan",
      original_name: "進撃の巨人",
      overview:
        "Many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the heroic members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!",
      poster_path: "/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10765, 10759],
      popularity: 239.418,
      first_air_date: "2013-04-07",
      vote_average: 8.658,
      vote_count: 6271,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/33Al50uZ9cZSddklcuHTaHmNxeE.jpg",
      id: 114924,
      name: "Time Bandits",
      original_name: "Time Bandits",
      overview:
        "Eleven-year-old Kevin's passion for history is put to the test when he joins a ragtag group of time-traveling thieves on a high-stakes and hilarious adventure.",
      poster_path: "/ahnTuygdAbjXvLKzLQlK2txosMX.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 10759, 35],
      popularity: 251.956,
      first_air_date: "2024-07-23",
      vote_average: 6.344,
      vote_count: 61,
      origin_country: ["NZ", "GB", "US"],
    },
    {
      backdrop_path: "/7sqFEDDmK1hG5m92upolcfQxy7R.jpg",
      id: 75006,
      name: "The Umbrella Academy",
      original_name: "The Umbrella Academy",
      overview:
        "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
      poster_path: "/qhcwrnnCnN8NE1N6XXKHFmveJR9.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765, 18],
      popularity: 586.325,
      first_air_date: "2019-02-15",
      vote_average: 8.56,
      vote_count: 9368,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/loEr0O5yKeldphTZy6IGJ8QfRGw.jpg",
      id: 230069,
      name: "Breathless",
      original_name: "Respira",
      overview:
        "A passionate medical team is devoted to saving lives in a bustling public hospital where tensions — and romance — keep their pulses racing.",
      poster_path: "/s6qEnmFxRqQQhjPAZPNHlwPc75y.jpg",
      media_type: "tv",
      adult: false,
      original_language: "es",
      genre_ids: [18],
      popularity: 375.154,
      first_air_date: "2024-08-30",
      vote_average: 9.2,
      vote_count: 14,
      origin_country: ["ES"],
    },
    {
      backdrop_path: "/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg",
      id: 1396,
      name: "Breaking Bad",
      original_name: "Breaking Bad",
      overview:
        "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18, 80],
      popularity: 854.14,
      first_air_date: "2008-01-20",
      vote_average: 8.913,
      vote_count: 14100,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/gArCVC4ML529WMCEqOXbALdQbUq.jpg",
      id: 203737,
      name: "Oshi No Ko",
      original_name: "【推しの子】",
      overview:
        "Dr. Goro is reborn as the son of the young starlet Ai Hoshino after her delusional stalker murders him. Now, he wants to help his new mother rise to the top, but what can a child do about the dark underbelly of the entertainment industry?",
      poster_path: "/mErHxLBgXK3FrfigrA19QFS1nbz.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 18],
      popularity: 356.44,
      first_air_date: "2023-04-12",
      vote_average: 8.331,
      vote_count: 192,
      origin_country: ["JP"],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
const mockedPopularMovies: IPopularMoviesResponse = {
  page: 1,
  results: [
    {
      backdrop_path: "/qr69tjjXcZLKjqD48aAq6FzBjf9.jpg",
      id: 1032823,
      title: "Trap",
      original_title: "Trap",
      overview: "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      poster_path: "/jwoaKYVqPgYemFpaANL941EF94R.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53],
      popularity: 780.546,
      release_date: "2024-07-31",
      video: false,
      vote_average: 6.506,
      vote_count: 661,
    },
    {
      backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      id: 365177,
      title: "Borderlands",
      original_title: "Borderlands",
      overview:
        "Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.",
      poster_path: "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35],
      popularity: 533.295,
      release_date: "2024-08-07",
      video: false,
      vote_average: 5.63,
      vote_count: 274,
    },
    {
      backdrop_path: "/qkEnklEGDFy4TRVhuHFn2DI2BP6.jpg",
      id: 930600,
      title: "The Deliverance",
      original_title: "The Deliverance",
      overview:
        "Ebony Jackson, a struggling single mother fighting her personal demons, moves her family into a new home for a fresh start. But when strange occurrences inside the home raise the suspicions of Child Protective Services and threaten to tear the family apart, Ebony soon finds herself locked in a battle for her life and the souls of her children.",
      poster_path: "/og1FteMFRInoQnlZeWqEn8XpXHh.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 87.205,
      release_date: "2024-08-16",
      video: false,
      vote_average: 6.548,
      vote_count: 114,
    },
    {
      backdrop_path: "/3VPeJgFASkb2pWcvUXMnhSY2wl5.jpg",
      id: 917496,
      title: "Beetlejuice Beetlejuice",
      original_title: "Beetlejuice Beetlejuice",
      overview:
        "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Beetlejuice, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
      poster_path: "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 27, 14],
      popularity: 481.905,
      release_date: "2024-09-04",
      video: false,
      vote_average: 6.9,
      vote_count: 15,
    },
    {
      backdrop_path: "/lkmkNVFGsRVKZs1MqKbE6zabXc4.jpg",
      id: 1226578,
      title: "Longlegs",
      original_title: "Longlegs",
      overview:
        "FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes an unexpected turn, revealing evidence of the occult. Harker discovers a personal connection to the killer and must stop him before he strikes again.",
      poster_path: "/5aj8vVGFwGVbQQs26ywhg4Zxk2L.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 27, 53],
      popularity: 1128.921,
      release_date: "2024-07-10",
      video: false,
      vote_average: 6.678,
      vote_count: 636,
    },
    {
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      id: 1022789,
      title: "Inside Out 2",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 12, 35],
      popularity: 1912.412,
      release_date: "2024-06-11",
      video: false,
      vote_average: 7.683,
      vote_count: 3255,
    },
    {
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      id: 945961,
      title: "Alien: Romulus",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 986.805,
      release_date: "2024-08-13",
      video: false,
      vote_average: 7.171,
      vote_count: 812,
    },
    {
      backdrop_path: "/dNplOw9U5IzlY7nNiaMS0JSVobp.jpg",
      id: 1029955,
      title: "Kinds of Kindness",
      original_title: "Kinds of Kindness",
      overview:
        "A triptych fable following a man without choice who tries to take control of his own life; a policeman who is alarmed that his wife who was missing-at-sea has returned and seems a different person; and a woman determined to find a specific someone with a special ability, who is destined to become a prodigious spiritual leader.",
      poster_path: "/8mmpltkcG9areafsQHXaURedno3.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 18],
      popularity: 320.886,
      release_date: "2024-05-30",
      video: false,
      vote_average: 6.699,
      vote_count: 485,
    },
    {
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      id: 533535,
      title: "Deadpool & Wolverine",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 878],
      popularity: 3965.179,
      release_date: "2024-07-24",
      video: false,
      vote_average: 7.77,
      vote_count: 2575,
    },
    {
      backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
      id: 718821,
      title: "Twisters",
      original_title: "Twisters",
      overview:
        "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
      poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 18],
      popularity: 1443.122,
      release_date: "2024-07-10",
      video: false,
      vote_average: 7.019,
      vote_count: 1220,
    },
    {
      backdrop_path: "/6IrZ3C8qSZ8Tbb32s41ReJOXpI0.jpg",
      id: 826510,
      title: "Harold and the Purple Crayon",
      original_title: "Harold and the Purple Crayon",
      overview:
        "Inside of his book, adventurous Harold can make anything come to life simply by drawing it. After he grows up and draws himself off the book's pages and into the physical world, Harold finds he has a lot to learn about real life.",
      poster_path: "/dEsuQOZwdaFAVL26RjgjwGl9j7m.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 14, 35],
      popularity: 602.68,
      release_date: "2024-07-31",
      video: false,
      vote_average: 6.787,
      vote_count: 75,
    },
    {
      backdrop_path: "/tCQfubckzzcuCbsGugkpLhfjS5z.jpg",
      id: 970347,
      title: "The Killer",
      original_title: "The Killer",
      overview:
        'Zee is a feared contract killer known as "the Queen of the Dead," but when she refuses to murder a young blind woman, she finds herself hunted both by criminal colleagues and a determined police detective.',
      poster_path: "/6PCnxKZZIVRanWb710pNpYVkCSw.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 53, 80],
      popularity: 302.992,
      release_date: "2024-08-22",
      video: false,
      vote_average: 6.381,
      vote_count: 80,
    },
    {
      backdrop_path: "/zVoLSd9K7ZdDJ4baKDDRt2cbNfG.jpg",
      id: 1114926,
      title: "The Good Half",
      original_title: "The Good Half",
      overview:
        "An emotionally distant writer returns to his hometown of Cleveland for his beloved mother’s funeral, after having spent years successfully avoiding interactions with his high-strung sister, bumbling but well-meaning father, and untrustworthy step-father. While in town, he forges a new relationship with a charming, energetic stranger who pushes him to realize that he can’t avoid conflict forever — with his family or within himself.",
      poster_path: "/iLkefl9aLo29ALVBbViRVyLo3WF.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 18],
      popularity: 9.411,
      release_date: "2024-07-23",
      video: false,
      vote_average: 5.3,
      vote_count: 3,
    },
    {
      backdrop_path: "/eHMh7kChaNeD4VTdMCXLJbRTzcI.jpg",
      id: 753342,
      title: "Napoleon",
      original_title: "Napoleon",
      overview:
        "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
      poster_path: "/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [36, 10752, 10749, 18],
      popularity: 192.331,
      release_date: "2023-11-22",
      video: false,
      vote_average: 6.427,
      vote_count: 2340,
    },
    {
      backdrop_path: "/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
      id: 348,
      title: "Alien",
      original_title: "Alien",
      overview:
        "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
      poster_path: "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 319.34,
      release_date: "1979-05-25",
      video: false,
      vote_average: 8.153,
      vote_count: 14416,
    },
    {
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      id: 519182,
      title: "Despicable Me 4",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 35, 28],
      popularity: 1732.199,
      release_date: "2024-06-20",
      video: false,
      vote_average: 7.26,
      vote_count: 1382,
    },
    {
      backdrop_path: "/Xky1fMOVseWAXXzr1ZREofJL0o.jpg",
      id: 1106052,
      title: "(Un)lucky Sisters",
      original_title: "Las hermanas fantásticas",
      overview:
        "After their father's death, estranged sisters stumble upon his hidden fortune, forcing them to decide whether to keep the money or do the right thing.",
      poster_path: "/bXcu53TWgU3rOGgzWpTIWLdNsDT.jpg",
      media_type: "movie",
      adult: false,
      original_language: "es",
      genre_ids: [35, 18],
      popularity: 129.282,
      release_date: "2024-08-30",
      video: false,
      vote_average: 6.227,
      vote_count: 11,
    },
    {
      backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      id: 786892,
      title: "Furiosa: A Mad Max Saga",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
      poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 878],
      popularity: 562.39,
      release_date: "2024-05-22",
      video: false,
      vote_average: 7.588,
      vote_count: 2929,
    },
    {
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      id: 653346,
      title: "Kingdom of the Planet of the Apes",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 12, 28],
      popularity: 616.962,
      release_date: "2024-05-08",
      video: false,
      vote_average: 7.137,
      vote_count: 2738,
    },
    {
      backdrop_path: "/wtd9gdvK36y2D3yAAchArknbIQu.jpg",
      id: 1216103,
      title: "Out Come the Wolves",
      original_title: "Out Come the Wolves",
      overview:
        "At a cabin deep in the wilderness, a weekend of hunting turns to mayhem and a fight for survival when a pack of wolves attack a man, his female best friend and her fiance.",
      poster_path: "/kDijoX2DQlymtUL44lCxJ1JLsGL.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53, 27, 28],
      popularity: 0.001,
      release_date: "2024-08-30",
      video: false,
      vote_average: 5.8,
      vote_count: 11,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
const mockedPopularAllMedia: IPopularMediaResponse = {
  page: 1,
  results: [
    {
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      id: 1022789,
      title: "Inside Out 2",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 12, 35],
      popularity: 2452.837,
      release_date: "2024-06-11",
      video: false,
      vote_average: 7.684,
      vote_count: 3227,
    },
    {
      backdrop_path: "/NNC08YmJFFlLi1prBkK8quk3dp.jpg",
      id: 84773,
      name: "The Lord of the Rings: The Rings of Power",
      original_name: "The Lord of the Rings: The Rings of Power",
      overview:
        "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
      poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10759, 10765, 18],
      popularity: 2374.751,
      first_air_date: "2022-09-01",
      vote_average: 7.3,
      vote_count: 2664,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
      id: 1032823,
      title: "Trap",
      original_title: "Trap",
      overview: "A father and teen daughter attend a pop concert, where they realize they're at the center of a dark and sinister event.",
      poster_path: "/jwoaKYVqPgYemFpaANL941EF94R.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [53],
      popularity: 557.533,
      release_date: "2024-07-31",
      video: false,
      vote_average: 6.5,
      vote_count: 622,
    },
    {
      backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
      id: 718821,
      title: "Twisters",
      original_title: "Twisters",
      overview:
        "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
      poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 18],
      popularity: 1891.741,
      release_date: "2024-07-10",
      video: false,
      vote_average: 7,
      vote_count: 1203,
    },
    {
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      id: 945961,
      title: "Alien: Romulus",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      poster_path: "/p9QhpqGrRWK1iksl1ZO1rKkrzFb.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 1189.05,
      release_date: "2024-08-13",
      video: false,
      vote_average: 7.1,
      vote_count: 794,
    },
    {
      backdrop_path: "/bizhlTVjifYQUu4Xrdt7m3TYr7d.jpg",
      id: 1226578,
      title: "Longlegs",
      original_title: "Longlegs",
      overview:
        "FBI Agent Lee Harker is assigned to an unsolved serial killer case that takes an unexpected turn, revealing evidence of the occult. Harker discovers a personal connection to the killer and must stop him before he strikes again.",
      poster_path: "/5aj8vVGFwGVbQQs26ywhg4Zxk2L.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 27, 53],
      popularity: 1515.397,
      release_date: "2024-07-10",
      video: false,
      vote_average: 6.635,
      vote_count: 609,
    },
    {
      backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
      id: 365177,
      title: "Borderlands",
      original_title: "Borderlands",
      overview:
        "Returning to her home planet, an infamous bounty hunter forms an unexpected alliance with a team of unlikely heroes. Together, they battle monsters and dangerous bandits to protect a young girl who holds the key to unimaginable power.",
      poster_path: "/865DntZzOdX6rLMd405R0nFkLmL.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35],
      popularity: 380.925,
      release_date: "2024-08-07",
      video: false,
      vote_average: 5.6,
      vote_count: 260,
    },
    {
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      id: 533535,
      title: "Deadpool & Wolverine",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 878],
      popularity: 5116.296,
      release_date: "2024-07-24",
      video: false,
      vote_average: 7.8,
      vote_count: 2562,
    },
    {
      backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
      id: 519182,
      title: "Despicable Me 4",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 35, 28],
      popularity: 2247.902,
      release_date: "2024-06-20",
      video: false,
      vote_average: 7.261,
      vote_count: 1369,
    },
    {
      backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      id: 786892,
      title: "Furiosa: A Mad Max Saga",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
      poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 878],
      popularity: 706.332,
      release_date: "2024-05-22",
      video: false,
      vote_average: 7.587,
      vote_count: 2920,
    },
    {
      backdrop_path: "/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg",
      id: 348,
      title: "Alien",
      original_title: "Alien",
      overview:
        "During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.",
      poster_path: "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 420.599,
      release_date: "1979-05-25",
      video: false,
      vote_average: 8.153,
      vote_count: 14408,
    },
    {
      backdrop_path: "/zB0g0VaRKHfRrvBT4ouHK5W967W.jpg",
      id: 956842,
      title: "Fly Me to the Moon",
      original_title: "Fly Me to the Moon",
      overview:
        "Sparks fly in all directions as marketing maven Kelly Jones, brought in to fix NASA's public image, wreaks havoc on Apollo 11 launch director Cole Davis' already difficult task of putting a man on the moon. When the White House deems the mission too important to fail, Jones is directed to stage a fake moon landing as backup, and the countdown truly begins.",
      poster_path: "/gjk8YdXpItoC1in53FCrZMFIuBx.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 35],
      popularity: 364.693,
      release_date: "2024-07-10",
      video: false,
      vote_average: 6.949,
      vote_count: 396,
    },
    {
      backdrop_path: "/9Piw6Zju39bn3enIDLZzPfjMTBR.jpg",
      id: 102621,
      name: "KAOS",
      original_name: "KAOS",
      overview:
        "As discord reigns on Mount Olympus and almighty Zeus spirals into paranoia, three mortals are destined to reshape the future of humankind.",
      poster_path: "/dDBTUSl3tRsOeKC1jZugBSFHy9I.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 10765, 18],
      popularity: 262.168,
      first_air_date: "2024-08-29",
      vote_average: 7.513,
      vote_count: 40,
      origin_country: ["GB"],
    },
    {
      backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
      id: 37854,
      name: "One Piece",
      original_name: "ワンピース",
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: "/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [10759, 35, 16],
      popularity: 205.714,
      first_air_date: "1999-10-20",
      vote_average: 8.72,
      vote_count: 4588,
      origin_country: ["JP"],
    },
    {
      backdrop_path: "/fmFPP1pXrV9gK4KRNk4KijT0QSx.jpg",
      id: 239287,
      name: "Terminator Zero",
      original_name: "ターミネーター 0",
      overview:
        "A warrior from a post-apocalyptic future travels to 1997 to protect an AI scientist being hunted by an unfeeling — and indestructible — cyborg.",
      poster_path: "/v4sbn6IsJGAIZNHjdB4CprvS7zo.jpg",
      media_type: "tv",
      adult: false,
      original_language: "ja",
      genre_ids: [16, 10765, 10759],
      popularity: 535.212,
      first_air_date: "2024-08-29",
      vote_average: 7.7,
      vote_count: 43,
      origin_country: ["US", "JP"],
    },
    {
      backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      id: 94997,
      name: "House of the Dragon",
      original_name: "House of the Dragon",
      overview:
        "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 18, 10759],
      popularity: 1226.708,
      first_air_date: "2022-08-21",
      vote_average: 8.395,
      vote_count: 4838,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
      id: 653346,
      title: "Kingdom of the Planet of the Apes",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 12, 28],
      popularity: 793.627,
      release_date: "2024-05-08",
      video: false,
      vote_average: 7.138,
      vote_count: 2724,
    },
    {
      backdrop_path: "/pzFbYJfqGKlGxOsDIIsUi6YxVQ.jpg",
      id: 1094138,
      title: "Jackpot!",
      original_title: "Jackpot!",
      overview:
        "In the near future, a 'Grand Lottery' has been established - the catch: kill the winner before sundown to legally claim their multi-billion dollar jackpot. When Katie Kim mistakenly finds herself with the winning ticket, she reluctantly joins forces with amateur lottery protection agent Noel Cassidy who must get her to sundown in exchange for a piece of her prize.",
      poster_path: "/fOsamTFIyGxjw1jLSKdZYxQBJOT.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 878],
      popularity: 1230.354,
      release_date: "2024-08-13",
      video: false,
      vote_average: 6.429,
      vote_count: 375,
    },
    {
      backdrop_path: "/9BQqngPfwpeAfK7c2H3cwIFWIVR.jpg",
      id: 1079091,
      title: "It Ends with Us",
      original_title: "It Ends with Us",
      overview:
        "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
      poster_path: "/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 18],
      popularity: 1312.259,
      release_date: "2024-08-07",
      video: false,
      vote_average: 6.836,
      vote_count: 232,
    },
    {
      backdrop_path: "/4ft6TR9wA6bra0RLL6G7JFDQ5t1.jpg",
      id: 704239,
      title: "The Union",
      original_title: "The Union",
      overview:
        "A New Jersey construction worker goes from regular guy to aspiring spy when his long-lost high school sweetheart recruits him for an espionage mission.",
      poster_path: "/d9CTnTHip1RbVi2OQbA2LJJQAGI.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35],
      popularity: 1441.314,
      release_date: "2024-08-15",
      video: false,
      vote_average: 6.266,
      vote_count: 509,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
